package com.wzzy.hosp.maven.project.hospital.funcionarios.anestesista;

public enum EspecialidadeAnestesista {

    ANESTESIA_GERAL,
    ANESTESIA_REGIONAL,
    ANESTESIA_LOCOREGIONAL,
    ANESTESIA_PEDIATRICA,
    ANESTESIA_OBSTETRICA,
    ANESTESIA_CARDIOVASCULAR,
    ANESTESIA_NEUROCIRURGICA,
    ANESTESIA_ORTOPEDICA,
    ANESTESIA_PARA_TRANSPLANTE,
    ANESTESIA_INTENSIVA,
    ANESTESIA_PARA_DOR,
    ANESTESIA_ONCOLOGICA,
    ANESTESIA_AMBULATORIAL,
    ANESTESIA_TORACICA,
    ANESTESIA_PLASTICA,
    ANESTESIA_UROLOGICA,
    ANESTESIA_HEPATO_BILIAR,
    ANESTESIA_RENAL,
    ANESTESIA_OTORRINOLARINGOLOGICA,
    ANESTESIA_MAXILO_FACIAL
}
