package com.wzzy.hosp.maven.project.hospital.funcionarios.fisioterapeuta;

public enum EspecialidadeFisioterapeuta {

    FISIOTERAPIA_ORTOPEDICA,
    FISIOTERAPIA_NEUROLOGICA,
    FISIOTERAPIA_RESPIRATORIA,
    FISIOTERAPIA_CARDIOVASCULAR,
    FISIOTERAPIA_PEDIATRICA,
    FISIOTERAPIA_GERIATRICA,
    FISIOTERAPIA_TRAUMATOLOGICA,
    FISIOTERAPIA_DESPORTIVA,
    FISIOTERAPIA_UROGINECOLOGICA,
    FISIOTERAPIA_OBSTETRICA,
    FISIOTERAPIA_ONCOLOGICA,
    FISIOTERAPIA_INTENSIVA,
    FISIOTERAPIA_DERMATOFUNCIONAL,
    FISIOTERAPIA_REUMATOLOGICA,
    FISIOTERAPIA_POSTURAL,
    FISIOTERAPIA_AQUIATICA,
    FISIOTERAPIA_FUNCIONAL,
    FISIOTERAPIA_VESTIBULAR,
    FISIOTERAPIA_HOMECARE, // Atendimento domiciliar
    FISIOTERAPIA_OCUPACIONAL
}
