package com.wzzy.hosp.maven.project.hospital.funcionarios.nutricionista;

public enum EspecialidadeNutricionista {
    NUTRICAO_CLINICA,
    NUTRICAO_HOSPITALAR,
    NUTRICAO_SPORTIVA,
    NUTRICAO_PEDIATRICA,
    NUTRICAO_GERIATRICA,
    NUTRICAO_MATERNO_INFANTIL,
    NUTRICAO_FUNCIONAL,
    NUTRICAO_ONCOLOGICA,
    NUTRICAO_ESTETICA,
    NUTRICAO_COLETIVA,
    NUTRICAO_VEGETARIANA,
    NUTRICAO_ANIMAL,
    NUTRICAO_NEONATAL,
    NUTRICAO_METABOLICA,
    NUTRICAO_CARDIOLOGICA,
    NUTRICAO_ENDOCRINOLOGICA,
    NUTRICAO_RENAL,
    NUTRICAO_TECNOLOGICA, // Relacionada ao desenvolvimento de novos alimentos
    NUTRICAO_ESCOLAR,
    NUTRICAO_COMPORTAMENTAL
}

