package com.wzzy.hosp.maven.project.hospital.funcionarios.radiologista;

public enum EspecialidadeRadiologista {

    RADIOLOGIA_CONVENCIONAL,
    RADIOLOGIA_INTERVENCIONISTA,
    RADIOLOGIA_MUSCULOESQUELETICA,
    RADIOLOGIA_NEURORRADIOLOGICA,
    RADIOLOGIA_PEDIATRICA,
    RADIOLOGIA_TORACICA,
    RADIOLOGIA_ABDOMINAL,
    RADIOLOGIA_MAMARIA,
    RADIOLOGIA_CARDIOVASCULAR,
    ULTRASSONOGRAFIA,
    TOMOGRAFIA_COMPUTADORIZADA,
    RESSONANCIA_MAGNETICA,
    MEDICINA_NUCLEAR,
    DENSITOMETRIA_OSSEA,
    RADIOLOGIA_ONCOLOGICA,
    RADIOLOGIA_ODONTOLOGICA,
    RADIOLOGIA_VETERINARIA
}
