package com.wzzy.hosp.maven.project.hospital.funcionarios.tecenfermangem;

public enum EspecialidadeTecnicoEnfermagem {

    TEC_ENFERMAGEM_GERAL,
    TEC_ENFERMAGEM_PEDIATRICA,
    TEC_ENFERMAGEM_GERIATRICA,
    TEC_ENFERMAGEM_NEONATAL,
    TEC_ENFERMAGEM_OBSTETRICA,
    TEC_ENFERMAGEM_INTENSIVA,
    TEC_ENFERMAGEM_CIRURGICA,
    TEC_ENFERMAGEM_ONCOLOGICA,
    TEC_ENFERMAGEM_CARDIOLOGICA,
    TEC_ENFERMAGEM_NEUROLOGICA,
    TEC_ENFERMAGEM_TRAUMATOLOGICA,
    TEC_ENFERMAGEM_PSIQUIATRICA,
    TEC_ENFERMAGEM_DOMICILIAR, // Home Care
    TEC_ENFERMAGEM_URGENCIA_EMERGENCIA,
    TEC_ENFERMAGEM_ORTOPEDICA,
    TEC_ENFERMAGEM_REABILITACAO,
    TEC_ENFERMAGEM_DO_TRABALHO,
    TEC_ENFERMAGEM_NEFROLOGICA,
    TEC_ENFERMAGEM_UROLOGICA,
    TEC_ENFERMAGEM_HEMODIALISE
}
