package com.wzzy.hosp.maven.project.hospital.funcionarios.farmaceutico;

public enum EspecialidadeFarmaceutico {

    FARMACIA_CLINICA,
    FARMACIA_HOSPITALAR,
    FARMACIA_ONCOLOGICA,
    FARMACIA_COMUNITARIA,
    FARMACIA_ESTETICA,
    FARMACIA_HOMEOPATICA,
    FARMACIA_INDUSTRIAL,
    FARMACIA_SANITARISTA,
    FARMACIA_NUCLEAR,
    FARMACOGENOMICA,
    FARMACOVIGILANCIA,
    FARMACOTERAPIA,
    ANALISES_CLINICAS,
    TOXICOLOGIA,
    MICROBIOLOGIA,
    IMUNOLOGIA,
    NUTRICAO_CLINICA, // Para atuação em farmácias que manipulam fórmulas nutricionais
    BIOTECNOLOGIA,
    ACUPUNTURA_FARMACEUTICA,
    LOGISTICA_FARMACEUTICA,
    FARMACIA_VETERINARIA,
    GESTAO_FARMACEUTICA
}
