package com.wzzy.hosp.maven.project.hospital.funcionarios.enfermeiro;

public enum EspecialidadeEnfermeiro {

    ENFERMAGEM_GERAL,
    ENFERMAGEM_PEDIATRICA,
    ENFERMAGEM_GERIATRICA,
    ENFERMAGEM_NEONATAL,
    ENFERMAGEM_OBSTETRICA,
    ENFERMAGEM_INTENSIVA,
    ENFERMAGEM_CIRURGICA,
    ENFERMAGEM_ONCOLOGICA,
    ENFERMAGEM_CARDIOLOGICA,
    ENFERMAGEM_NEUROLOGICA,
    ENFERMAGEM_TRAUMATOLOGICA,
    ENFERMAGEM_PSIQUIATRICA,
    ENFERMAGEM_DOMICILIAR, // Home Care
    ENFERMAGEM_URGENCIA_EMERGENCIA,
    ENFERMAGEM_ORTOPEDICA,
    ENFERMAGEM_REABILITACAO,
    ENFERMAGEM_DO_TRABALHO,
    ENFERMAGEM_NEFROLOGICA,
    ENFERMAGEM_UROLOGICA,
    ENFERMAGEM_HEMODIALISE,
    ENFERMAGEM_AUDITORIA,
    ENFERMAGEM_ESTETICA,
    ENFERMAGEM_SAUDE_PUBLICA,
    ENFERMAGEM_SAUDE_MENTAL,
    ENFERMAGEM_INFECTOLOGICA,
    ENFERMAGEM_PALIATIVA
}

